### ISSUE TITLE
Fallout 4 Game Mode Crashing

### ISSUE THREAD

**Issue by fireundubh** [z-edit/zedit#29]
Expanding a group with records in an authored plugin, the entire screen becomes blank and white. 

### Steps to Reproduce
1. Load an authored plugin.
2. Try to expand a group in that plugin that contains records.

The user has to reload the application at this point.

### Workaround
1. Load an authored plugin.
2. Expand a group in, for example, Fallout4.esm that contains records.
3. Expand a group in the authored plugin that contains records.

**Comment by fireundubh** [comment]
Another way to produce a blank white screen:

### Steps to Reproduce

1. Load any plugin.
2. Expand a group in, for example, Fallout4.esm that contains records.
3. Scroll the list with the mouse wheel.

**Comment by matortheeternal** [comment]
Unable to recreate and have not heard this issue reported by other users.  Scrolling with the mouse wheel does not cause a the application to crash to a blank screen, and neither does expanding a group in an "authored" plugin.

**Comment by matortheeternal** [comment]
Recreated issue by expanding a group in Fallout4.esm.  This appears to be an issue with the Fallout4 game mode which does not occur on other game modes.

**Comment by matortheeternal** [comment]
Alright, this is a very strange error.  I set up some try-catch blocks, and they don't seem to be catching any javascript level exceptions, so I think it must be an unhandled exception occurring in XEditLib.dll.  So I tried setting up some breakpoints and stepping through things, and the exception *stopped happening*.  I removed the breakpoints and the session was clean - could not get it to crash.  Restarted and removed the breakpoints and first expansion caused a crash.

This is looking like some kind of timing-related memory corruption.  Not going to be fun to try to figure out how/why it's happening.

**Comment by matortheeternal** [comment]
Noticed some weird error events reported in the console:

```
[7244:1228/122309.788:ERROR:CONSOLE(852)] "[object ErrorEvent]", source: chrome-devtools://devtools/bundled/inspector.js (852)
```

Going to try to create a release build just in case this is somehow related to the devtools/development environment.  May also try updating Electron.

**Comment by matortheeternal** [comment]
Tried release build - no luck.  Also tried updating Electron - still happens.

Not sure what the next step should be.  It appears the exception is occurring in one of the `scope.getNodeData` calls when the first group is expanded after loading plugins, but placing a breakpoint anywhere before or after or around this call causes the exception to not occur.

**Comment by matortheeternal** [comment]
Error hasn't been happening for awhile, I think we're in the clear on this one.
