### ISSUE TITLE
Unable to resolve records hardcoded into the game executable

### ISSUE THREAD

**Issue by ForsakenShell** [z-edit/zedit#36]
Certain records hardcoded within Fallout4.exe are present in Fallout4.Hardcoded.dat but unresolved by zEdit itself.

I found this issue specifically with AVIF 0x331 (Food) but the problem may exist for other records too.

**Comment by matortheeternal** [comment]
Currently not certain what the source of this issue is.  Will look into it.

**Comment by matortheeternal** [comment]
Fixed in [xedit-lib 3fa0866](https://github.com/matortheeternal/xedit-lib/commit/3fa0866e708247f03a395267e840c921d83482d8).
